### ISSUE TITLE
Docker Compose 

### ISSUE THREAD

**Issue by mouzzampk2014-zz** [vladimir-tutin/Plex-Auto-Collections#1]
Hi, Could you please create a docker compose for this project? Thank you

**Comment by meisnate12** [comment]
I know this is late but there a docker version using the fork [mza921/Plex-Auto-Collections](https://github.com/mza921/Plex-Auto-Collections) as well as many improvements and bug fixes

**Comment by mouzzampk2014-zz** [comment]
Thank you so much
